declare const HEditorMath: {
    PI: number;
    TWO_PI: number;
    PI_OVER_TWO: number;
    SIXTY_FOUR_KILOBYTES: number;
    toSNorm: (value: number, rangeMaximum: number) => number;
    signNotZero: (value: number) => number;
    zeroToTwoPi: (angle: number) => number;
    mod: (m: number, n: number) => number;
    cos: (radians: number) => number;
    sin: (radians: number) => number;
    toRadians: (degrees: number) => number;
    toDegrees: (radians: number) => number;
    RADIANS_PER_DEGREE: number;
    DEGREES_PER_RADIAN: number;
    EPSILON1: number;
    EPSILON2: number;
    EPSILON3: number;
    EPSILON4: number;
    EPSILON5: number;
    EPSILON6: number;
    EPSILON7: number;
    EPSILON8: number;
    EPSILON9: number;
    EPSILON10: number;
    EPSILON11: number;
    EPSILON12: number;
    EPSILON13: number;
    EPSILON14: number;
    EPSILON15: number;
    EPSILON16: number;
    EPSILON17: number;
    EPSILON18: number;
    EPSILON19: number;
    EPSILON20: number;
    EPSILON21: number;
    LUNAR_RADIUS: number;
    equalsEpsilon: (left: number, right: number, relativeEpsilon?: number, absoluteEpsilon?: number) => boolean;
    sign: (value: number) => number;
    clamp: (value: number, min: number, max: number) => number;
    acosClamped: (value: number) => number;
};
export default HEditorMath;
