import Context from './Context';
declare const PixelFormat: {
    RGBA: 6408;
    RGB: 6407;
    RG: 33319;
    RED: 6403;
    LUMINANCE: 6409;
    DEPTH_STENCIL: 34041;
    DEPTH_COMPONENT: 6402;
    LUMINANCE_ALPHA: 6410;
    ALPHA: 6406;
    RGB_DXT1: number;
    RGBA_DXT1: number;
    RGBA_DXT3: number;
    RGBA_DXT5: number;
    RGB_PVRTC_4BPPV1: number;
    RGB_PVRTC_2BPPV1: number;
    RGBA_PVRTC_4BPPV1: number;
    RGBA_PVRTC_2BPPV1: number;
    RGBA_ASTC: number;
    RGB_ETC1: number;
    RGB8_ETC2: number;
    RGBA8_ETC2_EAC: number;
    RGBA_BC7: number;
    flipY: (bufferView: Uint8Array, pixelFormat: number, pixelDatatype: number, width: number, height: number) => Float32Array<ArrayBuffer> | Uint32Array<ArrayBuffer> | Uint16Array<ArrayBuffer> | Uint8Array<ArrayBufferLike>;
    createTypedArray: (pixelFormat: number, pixelDatatype: number, width: number, height: number) => Float32Array<ArrayBuffer> | Uint8Array<ArrayBuffer> | Uint32Array<ArrayBuffer> | Uint16Array<ArrayBuffer>;
    validate: (pixelFormat: number) => boolean;
    isCompressedFormat: (pixelFormat: number) => boolean;
    toInternalFormat: (pixelFormat: number, pixelDatatype: number, context: Context) => number;
    isDepthFormat: (pixelFormat: number) => pixelFormat is 34041 | 6402;
    isDXTFormat: (pixelFormat: number) => boolean;
    isPVRTCFormat: (pixelFormat: number) => boolean;
    isASTCFormat: (pixelFormat: number) => boolean;
    isETC2Format: (pixelFormat: number) => boolean;
    isETC1Format: (pixelFormat: number) => boolean;
    isBC7Format: (pixelFormat: number) => boolean;
    compressedTextureSizeInBytes: (pixelFormat: number, width: number, height: number) => number;
    textureSizeInBytes: (pixelFormat: number, pixelDatatype: number, width: number, height: number) => number;
    componentsLength: (pixelFormat: number) => 1 | 2 | 3 | 4;
    alignmentInBytes: (pixelFormat: number, pixelDatatype: number, width: number) => 1 | 2 | 4;
};
export default PixelFormat;
