import { TextureOptions } from '../../type';
import Sampler from './Sampler';
import Cartesian2 from '../Core/Cartesian2';
export default class Texture {
    private _id;
    private _context;
    private _sampler;
    private _initialized;
    private _flipY;
    private _preMultiplyAlpha;
    private _sizeInBytes;
    private _textureFilterAnisotropic;
    private _textureTarget;
    private _texture;
    private _internalFormat;
    private _pixelFormat;
    private _pixelDatatype;
    private _width;
    private _height;
    private _dimensions;
    private _hasMipmap;
    get internalFormat(): number;
    get textureTarget(): number;
    get pixelFormat(): number;
    get pixelDatatype(): number;
    get id(): string;
    get sampler(): Sampler | undefined;
    get initialized(): boolean;
    get flipY(): boolean;
    get preMultiplyAlpha(): boolean;
    get sizeInBytes(): number;
    get width(): number;
    get height(): number;
    get dimensions(): Cartesian2;
    get hasMipmap(): boolean;
    constructor(options: TextureOptions);
    private _setupSampler;
    private _loadCompressedBufferSource;
    private _loadBufferSource;
    private _loadFramebufferSource;
    private _loadImageSource;
    private _loadNull;
    private _nextMipSize;
}
