import { GeometryOffsetAttribute, PrimitiveOptions, PrimitiveState, PrimitiveType } from '../../type';
import Cartesian3 from '../Core/Cartesian3';
import Matrix4 from '../Core/Matrix4';
import Appearance from './Appearance';
import FrameState from './FrameState';
import GeometryInstance from '../Core/GeometryInstance';
import Material from './Material';
import Geometry from '../Core/Geometry';
import BoundingSphere from '../Core/BoundingSphere';
import { PickOffsets } from './PrimitivePipeline';
import VertexArray from '../Renderer/VertexArray';
interface BoundingSphereAttributeIndices {
    center3DHigh: number;
    center3DLow: number;
    center2DHigh: number;
    center2DLow: number;
    radius: number;
}
interface AttributeIndices {
    [name: string]: number;
}
export default class Primitive {
    geometryInstances: GeometryInstance[] | GeometryInstance | undefined;
    readonly primitiveType: PrimitiveType;
    private _asynchronous;
    show: boolean;
    modelMatrix: Matrix4;
    cull: boolean;
    rtcCenter: Cartesian3 | undefined;
    readonly appearance: Appearance;
    readonly depthFailAppearance?: Appearance;
    _appearance: undefined | Appearance;
    _material: undefined | Material;
    _depthFailAppearance: undefined | Appearance;
    _depthFailMaterial: undefined | Material;
    _interleave: boolean;
    _releaseGeometryInstances: boolean;
    _allowPicking: boolean;
    private _compressVertices;
    _translucent: undefined;
    _state: PrimitiveState;
    private _createPickOffsets;
    private _vertexCacheOptimize;
    private _pickOffsets;
    private _modelMatrix;
    private _createBoundingVolumeFunction;
    get pickOffsets(): PickOffsets[] | undefined;
    get asynchronous(): boolean;
    get vertexCacheOptimize(): boolean;
    get compressVertices(): boolean;
    get releaseGeometryInstances(): boolean;
    set releaseGeometryInstances(releaseGeometryInstances: boolean);
    _geometries: Geometry[] | undefined;
    _error: undefined | string;
    _numberOfInstances: number;
    _boundingSpheres: BoundingSphere[];
    _boundingSphereWC: BoundingSphere[];
    _boundingSphereCV: BoundingSphere[];
    _boundingSphere2D: BoundingSphere[];
    _boundingSphereMorph: BoundingSphere[];
    _perInstanceAttributeCache: Map<string, number>;
    _instanceIds: string[];
    _lastPerInstanceAttributeIndex: number;
    _isDestroyed: boolean;
    _va: VertexArray[];
    _attributeLocations: undefined | {
        [key: string]: number;
    };
    _primitiveType: PrimitiveType;
    _frontFaceRS: undefined;
    _backFaceRS: undefined;
    _sp: undefined;
    _spDepthFail: undefined;
    _frontFaceDepthFailRS: undefined;
    _backFaceDepthFailRS: undefined;
    private _pickIds;
    _colorCommands: never[];
    _pickCommands: never[];
    _ready: boolean;
    private _batchTable;
    _batchTableAttributeIndices: AttributeIndices | undefined;
    _offsetInstanceExtend: undefined | GeometryOffsetAttribute[];
    _batchTableOffsetAttribute2DIndex: undefined | number;
    _batchTableOffsetsUpdated: boolean;
    _instanceBoundingSpheres: BoundingSphere[];
    _instanceBoundingSpheresCV: undefined | BoundingSphere[];
    _tempBoundingSpheres: undefined | BoundingSphere[];
    _recomputeBoundingSpheres: boolean;
    _batchTableBoundingSpheresUpdated: boolean;
    _batchTableBoundingSphereAttributeIndices: BoundingSphereAttributeIndices | undefined;
    constructor(options: PrimitiveOptions);
    update(frameState: FrameState): void;
    private recomputeBoundingSpheres;
    private _updateBoundingVolumes;
    private _transformBoundingSphere;
    private _createVertexArray;
    private _updateBatchTableOffsets;
    private _updateBatchTableBoundingSpheres;
    private _loadAsynchronous;
    private _loadSynchronous;
    private _setReady;
    private _cloneInstance;
    private _cloneGeometry;
    private _cloneAttribute;
    private _createBatchTable;
    private _getAttributeValue;
    private _getCommonPerInstanceAttributeNames;
}
export {};
