import { PrimitiveOptions, PrimitiveState, PrimitiveType } from '../../type';
import Cartesian3 from '../Core/Cartesian3';
import Matrix4 from '../Core/Matrix4';
import Appearance from './Appearance';
import GeometryInstance from './GeometryInstance';
import Material from './Material';
export default class Primitive {
    readonly geometryInstances: GeometryInstance[] | GeometryInstance;
    readonly primitiveType: PrimitiveType;
    show: boolean;
    modelMatrix: Matrix4;
    cull: boolean;
    rtcCenter: Cartesian3 | undefined;
    readonly appearance: Appearance;
    readonly depthFailAppearance?: Appearance;
    _appearance: undefined | Appearance;
    _material: undefined | Material;
    _depthFailAppearance: undefined | Appearance;
    _depthFailMaterial: undefined | Material;
    _vertexCacheOptimize: boolean;
    _interleave: boolean;
    _releaseGeometryInstances: boolean;
    _allowPicking: boolean;
    _asynchronous: boolean;
    _compressVertices: boolean;
    _translucent: undefined;
    _state: PrimitiveState;
    _geometries: GeometryInstance[];
    _error: undefined | string;
    _numberOfInstances: number;
    _boundingSpheres: Cartesian3[];
    _boundingSphereWC: Cartesian3[];
    _boundingSphereCV: Cartesian3[];
    _boundingSphere2D: Cartesian3[];
    _boundingSphereMorph: Cartesian3[];
    _perInstanceAttributeCache: Map<string, number>;
    _instanceIds: string[];
    _lastPerInstanceAttributeIndex: number;
    _isDestroyed: boolean;
    _va: never[];
    _attributeLocations: undefined;
    _primitiveType: undefined;
    _frontFaceRS: undefined;
    _backFaceRS: undefined;
    _sp: undefined;
    _spDepthFail: undefined;
    _frontFaceDepthFailRS: undefined;
    _backFaceDepthFailRS: undefined;
    _pickIds: never[];
    _colorCommands: never[];
    _pickCommands: never[];
    _ready: boolean;
    _batchTable: undefined;
    _batchTableAttributeIndices: undefined;
    _offsetInstanceExtend: undefined;
    _batchTableOffsetAttribute2DIndex: undefined;
    _batchTableOffsetsUpdated: boolean;
    _instanceBoundingSpheres: undefined;
    _instanceBoundingSpheresCV: undefined;
    _tempBoundingSpheres: undefined;
    _recomputeBoundingSpheres: boolean;
    _batchTableBoundingSphereUpdated: boolean;
    _batchTableBoundingSphereAttributeIndices: undefined;
    constructor(options: PrimitiveOptions);
}
